export const URLS = {
  LOGIN: import.meta.env.VITE_API_LOGIN,
  LOGOUT: import.meta.env.VITE_API_LOGOUT,
  API_USER: import.meta.env.VITE_API_USER,
  API_PERMISSION: import.meta.env.VITE_API_PERMISSION,
  API_ROLE: import.meta.env.VITE_API_ROLE,
  API_APPLICATION: import.meta.env.VITE_API_APPLICATION,
  API_ASIGN_PERM_ROLE: import.meta.env.VITE_API_ASIGN_PERM_ROLE,
  API_ASIGN_PERM_APP: import.meta.env.VITE_API_ASIGN_PERM_APP,
  API_ASIGN_PERM_USER: import.meta.env.VITE_API_ASIGN_PERM_USER,
  API_ASIGN_ROLE_USER: import.meta.env.VITE_API_ASIGN_ROLE_USER,
  API_GRANT_PERMISSIONS_ROLE: import.meta.env.VITE_API_GRANT_PERMISSIONS_ROLE,
  INCIDENT_API: import.meta.env.VITE_INCIDENT_API,
  FORGOT_PASSWORD: import.meta.env.VITE_API_FORGOT_PASSWORD,

  API_VERIFY_TOKEN: import.meta.env.VITE_API_VERIFY_TOKEN,
  API_REFRESH_TOKEN: import.meta.env.VITE_API_REFRESH_TOKEN,
};