version: '3.8'

networks:
  web:
    external: true
  traefik_internal:  # ← Utilise le même réseau que MySQL
    external: true

services:
  berp:
    build:
      context: /home/yvan/DockerRun/BERP  # ← Chemin vers votre code source
      dockerfile: Dockerfile
    image: berp_image:latest
    container_name: berp
    restart: unless-stopped
    # Supprimez le volume .env, mieux de copier le fichier dans l'image
    environment:
      - NODE_ENV=production
    labels:
      - traefik.http.routers.berp.rule=Host(`berp.bfcgroupsa.com`)
      - traefik.http.routers.berp.tls=true
      - traefik.http.routers.berp.tls.certresolver=lets-encrypt
      - traefik.http.services.berp.loadbalancer.server.port=3000  # ← CORRIGÉ : port de l'app
    networks:
      - traefik_internal  # ← Pour communiquer avec MySQL
      - web
    # depends_on supprimé car mysql et memcached sont dans d'autres projets